version: "3.8"
services:
  db:
    container_name: db
    image: mariadb:10
    expose:
      - "3306"
    environment:
      MARIADB_DATABASE: dice
      MARIADB_USER: djangouser
      MARIADB_ROOT_PASSWORD: pass123#
      MARIADB_PASSWORD: pass123#
      TZ: Asia/Seoul
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - docker
  app:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/usr/src/app
    working_dir : /usr/src/app/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - "db"
    depends_on:
      - db
    networks:
      - docker
  nextjs:
    container_name: nextjs
    build:
      context: ./dice-client-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./dice-client-app:/usr/src/next"
      - "/usr/src/next/node_modules"
      - "/usr/src/next/.next"
    networks:
      - docker
networks:
  docker: