# Generated by Django 4.2 on 2024-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafereviews',
            name='Rating',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
    ]
