# Generated by Django 4.2 on 2024-02-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafereviews',
            name='Cafe_ReviewID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='CafeID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='OperatingHour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='MenuItemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
