# Generated by Django 4.2 on 2024-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafereviews_cafe_reviewid_alter_cafes_cafeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='OperatingHour',
            field=models.CharField(max_length=50),
        ),
    ]
