# Generated by Django 4.2 on 2024-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafes_name_alter_cafes_operatinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='PhoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
